version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - graphql-server

  graphql-server:
    image: graphqlzero/graphql-server:latest
    ports:
      - "4000:4000"
