import React from "react";
import Header from "../common/components/Header";
import HeroSection from "../common/components/HeroSection";
import Head from "next/head";
import { useMediaQuery } from "react-responsive";
import styles from "../styles/Home.module.scss";

const Home: React.FC = () => {
  const isMobile = useMediaQuery({ query: "(max-width: 767px)" });

  return (
    <div className={styles.container}>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={`${styles.main} ${isMobile ? styles.mobile : ""}`}>
        <section className={styles.leftSection}>
          <HeroSection />
        </section>
        <section className={styles.rightSection}>
          <img
            src="/Illustration.png"
            alt="Illustration"
            className={styles.image}
          />
        </section>
      </main>
    </div>
  );
};

export default Home;
