import React from "react";
import Head from "next/head";
import Header from "../Header";
import { useMediaQuery } from "react-responsive";
import styles from "./index.module.scss";

interface DefaultLayoutProps {
  children: React.ReactNode;
}

const DefaultLayout: React.FC<DefaultLayoutProps> = ({ children }) => {
  const isMobile = useMediaQuery({ query: "(max-width: 767px)" });

  return (
    <div className={styles["default-layout"]}>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main
        className={`${styles["default-layout__main"]} ${
          isMobile ? styles["default-layout__main--mobile"] : ""
        }`}
      >
        {children}
      </main>
    </div>
  );
};

export default DefaultLayout;
